#ifndef ONM_TC_PLUGIN_SUBSCRIPTION_OPERATIONAL_H
#define ONM_TC_PLUGIN_SUBSCRIPTION_OPERATIONAL_H

#include <sysrepo_types.h>

int onm_tc_subscription_operational_acls_acl_aces_ace_statistics_matched_packets(sr_session_ctx_t *session, uint32_t sub_id, const char *module_name, const char *path, const char *request_xpath, uint32_t request_id, struct lyd_node **parent, void *private_data);
int onm_tc_subscription_operational_acls_acl_aces_ace_statistics_matched_octets(sr_session_ctx_t *session, uint32_t sub_id, const char *module_name, const char *path, const char *request_xpath, uint32_t request_id, struct lyd_node **parent, void *private_data);
int onm_tc_subscription_operational_acls_acl_aces_ace(sr_session_ctx_t *session, uint32_t sub_id, const char *module_name, const char *path, const char *request_xpath, uint32_t request_id, struct lyd_node **parent, void *private_data);
int onm_tc_subscription_operational_acls_acl(sr_session_ctx_t *session, uint32_t sub_id, const char *module_name, const char *path, const char *request_xpath, uint32_t request_id, struct lyd_node **parent, void *private_data);
int onm_tc_subscription_operational_acls_attachment_points_interface_ingress_acl_sets_acl_set_ace_statistics_name(sr_session_ctx_t *session, uint32_t sub_id, const char *module_name, const char *path, const char *request_xpath, uint32_t request_id, struct lyd_node **parent, void *private_data);
int onm_tc_subscription_operational_acls_attachment_points_interface_ingress_acl_sets_acl_set_ace_statistics_matched_packets(sr_session_ctx_t *session, uint32_t sub_id, const char *module_name, const char *path, const char *request_xpath, uint32_t request_id, struct lyd_node **parent, void *private_data);
int onm_tc_subscription_operational_acls_attachment_points_interface_ingress_acl_sets_acl_set_ace_statistics_matched_octets(sr_session_ctx_t *session, uint32_t sub_id, const char *module_name, const char *path, const char *request_xpath, uint32_t request_id, struct lyd_node **parent, void *private_data);
int onm_tc_subscription_operational_acls_attachment_points_interface_ingress_acl_sets_acl_set_ace_statistics(sr_session_ctx_t *session, uint32_t sub_id, const char *module_name, const char *path, const char *request_xpath, uint32_t request_id, struct lyd_node **parent, void *private_data);
int onm_tc_subscription_operational_acls_attachment_points_interface_ingress_acl_sets_acl_set(sr_session_ctx_t *session, uint32_t sub_id, const char *module_name, const char *path, const char *request_xpath, uint32_t request_id, struct lyd_node **parent, void *private_data);
int onm_tc_subscription_operational_acls_attachment_points_interface_egress_acl_sets_acl_set_ace_statistics_name(sr_session_ctx_t *session, uint32_t sub_id, const char *module_name, const char *path, const char *request_xpath, uint32_t request_id, struct lyd_node **parent, void *private_data);
int onm_tc_subscription_operational_acls_attachment_points_interface_egress_acl_sets_acl_set_ace_statistics_matched_packets(sr_session_ctx_t *session, uint32_t sub_id, const char *module_name, const char *path, const char *request_xpath, uint32_t request_id, struct lyd_node **parent, void *private_data);
int onm_tc_subscription_operational_acls_attachment_points_interface_egress_acl_sets_acl_set_ace_statistics_matched_octets(sr_session_ctx_t *session, uint32_t sub_id, const char *module_name, const char *path, const char *request_xpath, uint32_t request_id, struct lyd_node **parent, void *private_data);
int onm_tc_subscription_operational_acls_attachment_points_interface_egress_acl_sets_acl_set_ace_statistics(sr_session_ctx_t *session, uint32_t sub_id, const char *module_name, const char *path, const char *request_xpath, uint32_t request_id, struct lyd_node **parent, void *private_data);
int onm_tc_subscription_operational_acls_attachment_points_interface_egress_acl_sets_acl_set(sr_session_ctx_t *session, uint32_t sub_id, const char *module_name, const char *path, const char *request_xpath, uint32_t request_id, struct lyd_node **parent, void *private_data);
int onm_tc_subscription_operational_acls_attachment_points_interface(sr_session_ctx_t *session, uint32_t sub_id, const char *module_name, const char *path, const char *request_xpath, uint32_t request_id, struct lyd_node **parent, void *private_data);

#endif // ONM_TC_PLUGIN_SUBSCRIPTION_OPERATIONAL_H